import { ComicRankApiSuccessResponse } from '../../../interfaces/comicsInterface';

const dramaComicDatas: ComicRankApiSuccessResponse[] = [
  {
    data: {
      hasNext: true,
      count: 100,
      comicRankList: [
        {
          id: 5551016703033344,
          alias: 'sleepingman',
          title: '백억년을 자는 남자',
          artists: [
            {
              name: '수사반장',
              role: 'writer',
              email: null,
              id: 'ssdj2002',
            },
          ],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 188,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 1,
          previousRank: 6,
          updatedAt: 1660274229871,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5551016703033344/images/tall.jpg?width=130',
        },
        {
          id: 35,
          alias: 'ssdj2002',
          title: '김철수씨 이야기',
          artists: [
            {
              name: '수사반장',
              role: 'writer',
              email: null,
              id: 'ssdj2002',
            },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 40,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 2,
          previousRank: 1,
          updatedAt: 1667202579936,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/35/images/tall.jpg?width=130',
        },
        {
          id: 5053488885465088,
          alias: '2weeks',
          title: '2주간 재워주세요',
          artists: [{ name: '은하이', role: 'writer', email: null, id: 'eunhi' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: 'e',
          freedEpisodeSize: 61,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 3,
          previousRank: 5,
          updatedAt: 1666857435822,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5053488885465088/images/tall.jpg?width=130',
        },
        {
          id: 270,
          alias: 'again2002',
          title: '어게인2002 - 모두의 추억',
          artists: [{ name: '문요셉', role: 'writer', email: null, id: 'munyosep' }],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 41,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 4,
          previousRank: 3,
          updatedAt: 1550044676600,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/270/images/tall.jpg?width=130',
        },
        {
          id: 4609020734078976,
          alias: 'gahu_r',
          title: '삼국지 가후전 R',
          artists: [
            { name: '마사토끼', role: 'scripter', email: null, id: 'masa' },
            { name: '입개', role: 'painter', email: null, id: 'ipgae' },
          ],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 169,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 5,
          previousRank: 4,
          updatedAt: 1565590876343,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4609020734078976/images/tall.jpg?width=130',
        },
        {
          id: 4593648627417088,
          alias: 'from_nothing',
          title: '무명의 등불',
          artists: [{ name: '이재', role: 'writer', email: null, id: 'now_jay' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: 'xw',
          freedEpisodeSize: 8,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 6,
          previousRank: 2,
          updatedAt: 1645171344114,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4593648627417088/images/tall.jpg?width=130',
        },
        {
          id: 6406678520922112,
          alias: 'secretcontract',
          title: '시크릿 동맹',
          artists: [{ name: '레로', role: 'writer', email: null, id: 'lero' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 7,
          previousRank: 8,
          updatedAt: 1644732087504,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6406678520922112/images/tall.jpg?width=130',
        },
        {
          id: 6049192073035776,
          alias: 'cooksilver',
          title: '아버지의 집밥',
          artists: [{ name: '고리타', role: 'writer', email: null, id: 'gorita' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 128,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 8,
          previousRank: 17,
          updatedAt: 1660274236813,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6049192073035776/images/tall.jpg?width=130',
        },
        {
          id: 6704126837522432,
          alias: 'killing_me_tender',
          title: '킬링 미 텐더',
          artists: [
            { name: '마사토끼', role: 'scripter', email: null, id: 'masa' },
            { name: '보로콤', role: 'painter', email: null, id: 'borocom' },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 9,
          previousRank: 13,
          updatedAt: 1585812066820,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6704126837522432/images/tall.jpg?width=130',
        },
        {
          id: 4592592441638912,
          alias: 'tokyo_revengers',
          title: '도쿄 리벤저스',
          artists: [
            {
              name: '와쿠이 켄',
              role: 'writer',
              email: null,
              id: 'kenwakui',
            },
            {
              name: '학산문화사',
              role: 'publisher',
              email: null,
              id: 'haksan',
            },
          ],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 10,
          previousRank: 125,
          updatedAt: 1626067066643,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4592592441638912/images/tall.jpg?width=130',
        },
        {
          id: 5033976744640512,
          alias: 'lady_sherlock',
          title: '레이디 셜록',
          artists: [{ name: '김달', role: 'writer', email: null, id: 'kimdal' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 11,
          previousRank: 10,
          updatedAt: 1639039507322,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5033976744640512/images/tall.jpg?width=130',
        },
        {
          id: 5596823196008448,
          alias: 'look_at_me',
          title: '룩앳미',
          artists: [{ name: 'KONY', role: 'writer', email: null, id: 'kony' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 8,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 12,
          previousRank: 47,
          updatedAt: 1528945225517,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5596823196008448/images/tall.jpg?width=130',
        },
        {
          id: 5303631240036352,
          alias: '4bro_hainuzka',
          title: '하이누즈카 집안의 사남',
          artists: [
            {
              name: '미나야마 카에루',
              role: 'writer',
              email: null,
              id: 'minayamakaeru',
            },
            {
              name: '미디어팜',
              role: 'publisher',
              email: null,
              id: 'mediapalm',
            },
          ],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 13,
          previousRank: 375,
          updatedAt: 1621998727962,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5303631240036352/images/tall.jpg?width=130',
        },
        {
          id: 6269503840780288,
          alias: 'sexercise_15',
          title: '섹서사이즈[개정판]',
          artists: [
            {
              name: '최남새',
              role: 'scripter',
              email: null,
              id: 'choenamsae',
            },
            { name: '슈룹', role: 'painter', email: null, id: 'shuroop' },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 14,
          previousRank: 14,
          updatedAt: 1617357062741,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6269503840780288/images/tall.jpg?width=130',
        },
        {
          id: 5292498940919808,
          alias: 'daily_15',
          title: '일상생활 가능하세요?[개정판]',
          artists: [
            {
              name: 'Alice Crazy',
              role: 'writer',
              email: null,
              id: 'alicecrazy',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 15,
          previousRank: 18,
          updatedAt: 1620956348589,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5292498940919808/images/tall.jpg?width=130',
        },
        {
          id: 5793662341218304,
          alias: 'aram',
          title: '아람이랑 삽니다!',
          artists: [{ name: '콕', role: 'writer', email: null, id: 'zoz202' }],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 12,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 16,
          previousRank: 34,
          updatedAt: 1666767120243,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5793662341218304/images/tall.jpg?width=130',
        },
        {
          id: 5103025959534592,
          alias: 'there_is_or_isnt',
          title: '난 있잖아 넌 없잖아',
          artists: [
            { name: 'PJS', role: 'scripter', email: null, id: 'pjs' },
            { name: '유종표', role: 'painter', email: null, id: 'chuck' },
            { name: '1535', role: 'publisher', email: null, id: '1535' },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 17,
          previousRank: 76,
          updatedAt: 1626420262334,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5103025959534592/images/tall.jpg?width=130',
        },
        {
          id: 5906730984996864,
          alias: 'vanilla_15',
          title: '하드코어 바닐라[개정판]',
          artists: [{ name: '유명', role: 'writer', email: null, id: 'youmy' }],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 18,
          previousRank: 95,
          updatedAt: 1617357366159,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5906730984996864/images/tall.jpg?width=130',
        },
        {
          id: 5683372882984960,
          alias: 'takagi',
          title: '장난을 잘 치는 전 타카기 양',
          artists: [
            {
              name: '야마모토 소이치로',
              role: 'writer',
              email: null,
              id: 'soichiroyamamoto',
            },
            { name: 'DCW', role: 'publisher', email: null, id: 'dcw' },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 6,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 19,
          previousRank: 138,
          updatedAt: 1610940281397,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5683372882984960/images/tall.jpg?width=130',
        },
        {
          id: 4625200343023616,
          alias: 'watchguy',
          title: '왓치가이',
          artists: [
            { name: '마사토끼', role: 'scripter', email: null, id: 'masa' },
            { name: 'ASURA', role: 'painter', email: null, id: 'asura' },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 11,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 20,
          previousRank: 49,
          updatedAt: 1662456774749,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4625200343023616/images/tall.jpg?width=130',
        },
      ],
    },
  },
  {
    data: {
      hasNext: true,
      count: 100,
      comicRankList: [
        {
          id: 5783553740963840,
          alias: 'burnit',
          title: '안아줄게 (Burn It)',
          artists: [
            { name: 'HYEYA', role: 'scripter', email: null, id: 'hyeya' },
            {
              name: 'west dog alcohol',
              role: 'painter',
              email: null,
              id: 'westdogalcohol',
            },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 21,
          previousRank: 66,
          updatedAt: 1646902739946,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5783553740963840/images/tall.jpg?width=130',
        },
        {
          id: 4900168845819904,
          alias: 'touch_on_15',
          title: '만져서 봉인해제[개정판]',
          artists: [{ name: '짐티지', role: 'writer', email: null, id: 'zimtigee' }],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 22,
          previousRank: 111,
          updatedAt: 1620956409727,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4900168845819904/images/tall.jpg?width=130',
        },
        {
          id: 5486888498561024,
          alias: 'yakumo_rice',
          title: '야쿠모 씨는 밥을 먹이고 싶어.',
          artists: [
            {
              name: '사토미 유',
              role: 'writer',
              email: null,
              id: 'usatomi',
            },
            {
              name: '학산문화사',
              role: 'publisher',
              email: null,
              id: 'haksan',
            },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 23,
          previousRank: 183,
          updatedAt: 1580352072656,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5486888498561024/images/tall.jpg?width=130',
        },
        {
          id: 6277422262321152,
          alias: '27_minus_10',
          title: '27-10',
          artists: [
            { name: 'AJS', role: 'writer', email: null, id: 'ajs' },
            {
              name: '써머폴',
              role: 'publisher',
              email: null,
              id: 'summerfall',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: 'n',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 24,
          previousRank: 16,
          updatedAt: 1671423417436,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6277422262321152/images/tall.jpg?width=130',
        },
        {
          id: 5257433893830656,
          alias: 'ugly',
          title: '못생겨서 좋겠다',
          artists: [{ name: '허세녀', role: 'writer', email: null, id: 'gjtpsu' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 14,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 25,
          previousRank: 25,
          updatedAt: 1621393995601,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5257433893830656/images/tall.jpg?width=130',
        },
        {
          id: 6080299074584576,
          alias: 'eunsoo',
          title: '은수',
          artists: [
            {
              name: '작업실 시보',
              role: 'writer',
              email: null,
              id: 'studio_sibo',
            },
          ],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 26,
          previousRank: 26,
          updatedAt: 1617613478932,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6080299074584576/images/tall.jpg?width=130',
        },
        {
          id: 4898410625892352,
          alias: 'unbalancex3',
          title: '언밸런스X3',
          artists: [
            {
              name: '임달영',
              role: 'scripter',
              email: null,
              id: 'imdalyoung',
            },
            {
              name: '이수현',
              role: 'painter',
              email: null,
              id: 'leesoohyun',
            },
            {
              name: '디투컴퍼니',
              role: 'label',
              email: null,
              id: 'D2Company',
            },
            {
              name: '디투컴퍼니',
              role: 'publisher',
              email: null,
              id: 'D2Company',
            },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 8,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 27,
          previousRank: 62,
          updatedAt: 1554871127636,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4898410625892352/images/tall.jpg?width=130',
        },
        {
          id: 5096934880051200,
          alias: 'with_my_knight',
          title: '나의 기사님이랑',
          artists: [{ name: '변태중년', role: 'writer', email: null, id: 'hhhhh' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 28,
          previousRank: 68,
          updatedAt: 1610525065622,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5096934880051200/images/tall.jpg?width=130',
        },
        {
          id: 6501321411526656,
          alias: 'madangalbum',
          title: '마당 씨의 가족 앨범',
          artists: [
            {
              name: '홍연식',
              role: 'writer',
              email: null,
              id: 'kiaoraworld',
            },
          ],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 29,
          previousRank: 88,
          updatedAt: 1610005309751,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6501321411526656/images/tall.jpg?width=130',
        },
        {
          id: 5962436329144320,
          alias: 'iljin_15',
          title: '일진녀 과외하기[개정판]',
          artists: [
            { name: 'over.J', role: 'scripter', email: null, id: 'overj' },
            { name: '최태영', role: 'painter', email: null, id: 'tychoi' },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 30,
          previousRank: 109,
          updatedAt: 1620956453881,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5962436329144320/images/tall.jpg?width=130',
        },
        {
          id: 5209921039171584,
          alias: 'heromanager_15',
          title: '히어로 매니저[개정판]',
          artists: [
            {
              name: '강백수',
              role: 'scripter',
              email: null,
              id: 'jumpingcat87',
            },
            {
              name: 'MMCNOKO',
              role: 'painter',
              email: null,
              id: 'dlgksk6965',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 31,
          previousRank: 19,
          updatedAt: 1621230103180,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5209921039171584/images/tall.jpg?width=130',
        },
        {
          id: 5717543693647872,
          alias: 'reject_15',
          title: '거절 못하는 여자[개정판]',
          artists: [
            {
              name: '나인티스매거진',
              role: 'scripter',
              email: null,
              id: 'magazine',
            },
            {
              name: '가나다라',
              role: 'painter',
              email: null,
              id: 'ganadara',
            },
          ],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 32,
          previousRank: 158,
          updatedAt: 1617356931790,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5717543693647872/images/tall.jpg?width=130',
        },
        {
          id: 5364870312165376,
          alias: 'personal_difference',
          title: '개인차 있습니다',
          artists: [
            {
              name: '히구라시 키노코',
              role: 'writer',
              email: null,
              id: 'kinokohigurashi',
            },
            {
              name: '시프트코믹스',
              role: 'publisher',
              email: null,
              id: 'shiftcomics',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 33,
          previousRank: 454,
          updatedAt: 1611912052599,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5364870312165376/images/tall.jpg?width=130',
        },
        {
          id: 5917457429364736,
          alias: 'levue_dan',
          title: '레뷰단!',
          artists: [
            {
              name: '나카무라 세이코',
              role: 'writer',
              email: null,
              id: 'seikonakamura',
            },
            {
              name: '서울미디어코믹스',
              role: 'publisher',
              email: null,
              id: 'seoulmediacomics',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: 'n',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 34,
          previousRank: 24,
          updatedAt: 1670493164244,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5917457429364736/images/tall.jpg?width=130',
        },
        {
          id: 5125706636984320,
          alias: 'dear_teacher',
          title: '은사',
          artists: [{ name: '이재', role: 'writer', email: null, id: 'now_jay' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 12,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 35,
          previousRank: 35,
          updatedAt: 1625022240296,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5125706636984320/images/tall.jpg?width=130',
        },
        {
          id: 5487695569879040,
          alias: 'pandoras_choice',
          title: '판도라의 선택',
          artists: [{ name: '유도리', role: 'writer', email: null, id: 'yudori' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: 'i',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 36,
          previousRank: 36,
          updatedAt: 1563092314760,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5487695569879040/images/tall.jpg?width=130',
        },
        {
          id: 4920991700090880,
          alias: 'fakerunway',
          title: '런웨이는 거짓말로 시작된다',
          artists: [{ name: '지우너', role: 'writer', email: null, id: 'jiwooner' }],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 13,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 37,
          previousRank: 37,
          updatedAt: 1628154634406,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4920991700090880/images/tall.jpg?width=130',
        },
        {
          id: 4964897716830208,
          alias: 'choco',
          title: '달콤한 나의 초콜릿',
          artists: [{ name: '한민기', role: 'writer', email: null, id: 'minki_Han' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 38,
          previousRank: 38,
          updatedAt: 1602752140259,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4964897716830208/images/tall.jpg?width=130',
        },
        {
          id: 5533113486409728,
          alias: '3girls',
          title: '삼작미인가',
          artists: [{ name: '므앵갱', role: 'writer', email: null, id: 'muanggang' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 12,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 39,
          previousRank: 39,
          updatedAt: 1623208036134,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5533113486409728/images/tall.jpg?width=130',
        },
        {
          id: 5785192695070720,
          alias: 'sweetmom',
          title: '고고 스윗맘',
          artists: [{ name: '뚠뚜루', role: 'writer', email: null, id: 'ddun' }],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 40,
          previousRank: 40,
          updatedAt: 1550041245723,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5785192695070720/images/tall.jpg?width=130',
        },
      ],
    },
  },
  {
    data: {
      hasNext: true,
      count: 100,
      comicRankList: [
        {
          id: 6624158499995648,
          alias: 'raspberry',
          title: '라즈베리 샌드위치',
          artists: [{ name: '차우민', role: 'writer', email: null, id: 'chaumin' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 41,
          previousRank: 41,
          updatedAt: 1626418084248,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6624158499995648/images/tall.jpg?width=130',
        },
        {
          id: 5784184712069120,
          alias: 'odyssey',
          title: '오디세이',
          artists: [{ name: '갈로아', role: 'writer', email: null, id: 'Galois' }],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 42,
          previousRank: 42,
          updatedAt: 1542855607990,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5784184712069120/images/tall.jpg?width=130',
        },
        {
          id: 5771872688144384,
          alias: 'rookie',
          title: '초년의 맛',
          artists: [{ name: '앵무', role: 'writer', email: null, id: 'vnddjs' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: 'i',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 43,
          previousRank: 43,
          updatedAt: 1602321641534,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5771872688144384/images/tall.jpg?width=130',
        },
        {
          id: 5835837207216128,
          alias: 'private',
          title: '볕내',
          artists: [{ name: '박혜민', role: 'writer', email: null, id: 'hyemin' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: 'i',
          freedEpisodeSize: 12,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 44,
          previousRank: 44,
          updatedAt: 1578041704368,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5835837207216128/images/tall.jpg?width=130',
        },
        {
          id: 5229324152864768,
          alias: 'underpainting',
          title: '언더페인팅',
          artists: [{ name: '내리', role: 'writer', email: null, id: 'nary' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 45,
          previousRank: 45,
          updatedAt: 1537412401767,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5229324152864768/images/tall.jpg?width=130',
        },
        {
          id: 313,
          alias: 'girlgongmyung',
          title: '여자 제갈량',
          artists: [{ name: '김달', role: 'writer', email: null, id: 'kimdal' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 46,
          previousRank: 46,
          updatedAt: 1639039109200,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/313/images/tall.jpg?width=130',
        },
        {
          id: 4540744709832704,
          alias: 'sea_to_the_boy',
          title: '바다가 소년에게',
          artists: [
            {
              name: '이현민',
              role: 'scripter',
              email: null,
              id: 'hyunmin',
            },
            {
              name: '이진영',
              role: 'painter',
              email: null,
              id: 'leejinyoung',
            },
            {
              name: 'JQ스튜디오',
              role: 'publisher',
              email: null,
              id: 'jqstudio',
            },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 47,
          previousRank: 48,
          updatedAt: 1622465438202,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4540744709832704/images/tall.jpg?width=130',
        },
        {
          id: 5004416026673152,
          alias: 'little_castle',
          title: '작은 성 : 시들지 않는 꽃',
          artists: [{ name: '마윤', role: 'writer', email: null, id: 'mayoon' }],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 7,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 48,
          previousRank: 50,
          updatedAt: 1520223477488,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5004416026673152/images/tall.jpg?width=130',
        },
        {
          id: 4865266188943360,
          alias: 'qr',
          title: '배달부들',
          artists: [{ name: '우주', role: 'writer', email: null, id: '3114' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 49,
          previousRank: 51,
          updatedAt: 1641454989965,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4865266188943360/images/tall.jpg?width=130',
        },
        {
          id: 6647348622786560,
          alias: 'makeup_artist_in_chosun',
          title: '매분구',
          artists: [
            { name: '요신', role: 'scripter', email: null, id: 'yosin' },
            {
              name: '배로빈',
              role: 'painter',
              email: null,
              id: 'baerobin',
            },
            {
              name: '키다리스튜디오',
              role: 'publisher',
              email: null,
              id: 'kidaristudio',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 50,
          previousRank: 52,
          updatedAt: 1659414999293,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6647348622786560/images/tall.jpg?width=130',
        },
        {
          id: 4866977410056192,
          alias: 'lopamudra',
          title: '카페 로파무드라',
          artists: [
            {
              name: '언발란스',
              role: 'writer',
              email: null,
              id: 'unbalance',
            },
          ],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 8,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 51,
          previousRank: 53,
          updatedAt: 1528180680718,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4866977410056192/images/tall.jpg?width=130',
        },
        {
          id: 4767600603561984,
          alias: 'spys',
          title: '조국과 민족',
          artists: [{ name: '강태진', role: 'writer', email: null, id: 'bbanss' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: 'w',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 52,
          previousRank: 27,
          updatedAt: 1661761631193,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4767600603561984/images/tall.jpg?width=130',
        },
        {
          id: 5072753211342848,
          alias: 'sheela_gun',
          title: '쉴라 건',
          artists: [
            {
              name: '마사토끼',
              role: 'scripter',
              email: null,
              id: 'masa',
            },
            { name: '밀', role: 'painter', email: null, id: 'meal' },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 53,
          previousRank: 54,
          updatedAt: 1554701675940,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5072753211342848/images/tall.jpg?width=130',
        },
        {
          id: 5714360039440384,
          alias: 'gentleman',
          title: '명동젠틀맨',
          artists: [
            {
              name: '미스와플',
              role: 'scripter',
              email: null,
              id: 'misswaffle',
            },
            { name: '직가', role: 'painter', email: null, id: 'jikka' },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 54,
          previousRank: 55,
          updatedAt: 1664956122317,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5714360039440384/images/tall.jpg?width=130',
        },
        {
          id: 4749772755894272,
          alias: 'insaeyes',
          title: '인사의 눈',
          artists: [{ name: '도국', role: 'writer', email: null, id: 'iqzeo619' }],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 55,
          previousRank: 56,
          updatedAt: 1644820049461,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4749772755894272/images/tall.jpg?width=130',
        },
        {
          id: 5413693209968640,
          alias: 'genie',
          title: '당신의 지니',
          artists: [{ name: '임현정', role: 'writer', email: null, id: 'maz7112' }],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 8,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 56,
          previousRank: 57,
          updatedAt: 1653906998758,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5413693209968640/images/tall.jpg?width=130',
        },
        {
          id: 6395077662867456,
          alias: 'hirugao',
          title: '메꽃 ~오후 3시의 연인들~',
          artists: [{ name: '김정현', role: 'writer', email: null, id: 'kino917' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 57,
          previousRank: 58,
          updatedAt: 1556858083856,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6395077662867456/images/tall.jpg?width=130',
        },
        {
          id: 5624953393643520,
          alias: 'kuhakuki',
          title: '공백기',
          artists: [
            {
              name: '전민지',
              role: 'writer',
              email: null,
              id: 'junminji',
            },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 14,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 58,
          previousRank: 59,
          updatedAt: 1612427925510,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5624953393643520/images/tall.jpg?width=130',
        },
        {
          id: 4821808825892864,
          alias: 'sangsangdang',
          title: '상상당 한의원',
          artists: [
            {
              name: '서영애',
              role: 'writer',
              email: null,
              id: 'joanmiro',
            },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: 'iw',
          freedEpisodeSize: 6,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 59,
          previousRank: 28,
          updatedAt: 1646707861959,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4821808825892864/images/tall.jpg?width=130',
        },
        {
          id: 6575268919574528,
          alias: 'how_to_live',
          title: '올바른 인생을 살아가는 법',
          artists: [
            {
              name: '마사토끼',
              role: 'scripter',
              email: null,
              id: 'masa',
            },
            { name: '김빛', role: 'painter', email: null, id: 'kimbit' },
          ],
          schedule: { periods: ['THU'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 60,
          previousRank: 22,
          updatedAt: 1666575438848,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6575268919574528/images/tall.jpg?width=130',
        },
      ],
    },
  },
  {
    data: {
      hasNext: true,
      count: 100,
      comicRankList: [
        {
          id: 200,
          alias: 'rebound_ball',
          title: '튄 공',
          artists: [{ name: '이삼', role: 'writer', email: null, id: 'no23' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 22,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 61,
          previousRank: 60,
          updatedAt: 1546497839690,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/200/images/tall.jpg?width=130',
        },
        {
          id: 5367809780613120,
          alias: 'by_myself',
          title: '홀로',
          artists: [{ name: '이삼', role: 'writer', email: null, id: 'no23' }],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 62,
          previousRank: 61,
          updatedAt: 1575531526544,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5367809780613120/images/tall.jpg?width=130',
        },
        {
          id: 6,
          alias: 'm_street_no9',
          title: '마들레느가 9번지',
          artists: [{ name: '진혜리', role: 'writer', email: null, id: 'jhlart' }],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 261,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 63,
          previousRank: 12,
          updatedAt: 1643265816537,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/6/images/tall.jpg?width=130',
        },
        {
          id: 5988270749908992,
          alias: 'bl',
          title: '튀어나왔어요, BL만화!',
          artists: [
            {
              name: '마롭-믹',
              role: 'writer',
              email: null,
              id: 'marobmik',
            },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 64,
          previousRank: 63,
          updatedAt: 1631260814642,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5988270749908992/images/tall.jpg?width=130',
        },
        {
          id: 6471369140338688,
          alias: 'engagement',
          title: '약혼자는 동거중',
          artists: [
            {
              name: '임달영',
              role: 'scripter',
              email: null,
              id: 'imdalyoung',
            },
            {
              name: '이수현',
              role: 'painter',
              email: null,
              id: 'leesoohyun',
            },
            {
              name: '디투컴퍼니',
              role: 'label',
              email: null,
              id: 'D2Company',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 65,
          previousRank: 64,
          updatedAt: 1577408940674,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6471369140338688/images/tall.jpg?width=130',
        },
        {
          id: 4981925070569472,
          alias: 'fallthrough',
          title: '들개-불발',
          artists: [
            {
              name: '용현',
              role: 'scripter',
              email: null,
              id: 'yonghyun',
            },
            {
              name: '김정현',
              role: 'painter',
              email: null,
              id: 'kino917',
            },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 7,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 66,
          previousRank: 65,
          updatedAt: 1622702376475,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4981925070569472/images/tall.jpg?width=130',
        },
        {
          id: 4995133933682688,
          alias: 'timeline',
          title: '타임라인',
          artists: [{ name: '헛둘', role: 'writer', email: null, id: 'extaxi' }],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 67,
          previousRank: 67,
          updatedAt: 1661760911705,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4995133933682688/images/tall.jpg?width=130',
        },
        {
          id: 6013643236114432,
          alias: 'our_home',
          title: '작전본부: 우리 집',
          artists: [{ name: '청혈구', role: 'writer', email: null, id: 'bbc' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 49,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 68,
          previousRank: 15,
          updatedAt: 1653010695440,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6013643236114432/images/tall.jpg?width=130',
        },
        {
          id: 5154759719256064,
          alias: '2nd_manhwaking_pandoras_choice',
          title: '판도라의 선택 [제2회 세계만화공모전 수상작]',
          artists: [{ name: '유도리', role: 'writer', email: null, id: 'yudori' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 69,
          previousRank: 69,
          updatedAt: 1520223483114,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5154759719256064/images/tall.jpg?width=130',
        },
        {
          id: 5744074253533184,
          alias: 'boss_neighbor',
          title: '사장님은 이웃사촌',
          artists: [
            {
              name: '임달영',
              role: 'scripter',
              email: null,
              id: 'imdalyoung',
            },
            {
              name: '심원용',
              role: 'painter',
              email: null,
              id: 'Sim Won-yong',
            },
            {
              name: '디투컴퍼니',
              role: 'publisher',
              email: null,
              id: 'D2Company',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 70,
          previousRank: 29,
          updatedAt: 1560489820830,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5744074253533184/images/tall.jpg?width=130',
        },
        {
          id: 10,
          alias: 'heima',
          title: '헤이마',
          artists: [
            {
              name: '작업실 시보',
              role: 'writer',
              email: null,
              id: 'studio_sibo',
            },
          ],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 71,
          previousRank: 70,
          updatedAt: 1540264960401,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/10/images/tall.jpg?width=130',
        },
        {
          id: 33,
          alias: 'gahu',
          title: '가후전',
          artists: [
            {
              name: '마사토끼',
              role: 'scripter',
              email: null,
              id: 'masa',
            },
            { name: '배민수', role: 'painter', email: null, id: 'brave' },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 72,
          previousRank: 71,
          updatedAt: 1550208017474,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/33/images/tall.jpg?width=130',
        },
        {
          id: 5939837511663616,
          alias: 'fishnight',
          title: '물고기의 밤',
          artists: [
            {
              name: '정은수',
              role: 'writer',
              email: null,
              id: 'jungeunsu',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 73,
          previousRank: 72,
          updatedAt: 1541646002872,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5939837511663616/images/tall.jpg?width=130',
        },
        {
          id: 5019053195001856,
          alias: 'gods_glue',
          title: '신의 접착제',
          artists: [
            { name: '기드온', role: 'writer', email: null, id: 'gideon' },
            {
              name: '서울미디어코믹스',
              role: 'publisher',
              email: null,
              id: 'seoulmediacomics',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 74,
          previousRank: 73,
          updatedAt: 1573551093653,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5019053195001856/images/tall.jpg?width=130',
        },
        {
          id: 5057602952429568,
          alias: 'sophomoricillness',
          title: '최강! 중2병 그녀',
          artists: [{ name: '영식', role: 'writer', email: null, id: '0sick' }],
          schedule: { periods: ['SAT'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 75,
          previousRank: 74,
          updatedAt: 1649322533784,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5057602952429568/images/tall.jpg?width=130',
        },
        {
          id: 5123868419817472,
          alias: 'revenge_of_wife',
          title: '아내의 복수를 대신하다',
          artists: [
            { name: '밀헨', role: 'scripter', email: null, id: 'milhen' },
            { name: '매타', role: 'painter', email: null, id: 'maeta' },
            {
              name: '디투컴퍼니',
              role: 'publisher',
              email: null,
              id: 'd2company',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 76,
          previousRank: 75,
          updatedAt: 1554870845452,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5123868419817472/images/tall.jpg?width=130',
        },
        {
          id: 4529839812378624,
          alias: 'snowingflower',
          title: '눈이 나려 꽃 [연재]',
          artists: [
            {
              name: '임해연',
              role: 'writer',
              email: null,
              id: 'yimhaeyeon',
            },
          ],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 77,
          previousRank: 77,
          updatedAt: 1623208069752,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4529839812378624/images/tall.jpg?width=130',
        },
        {
          id: 6262255336620032,
          alias: 'the_golden_hour',
          title: '골든아워',
          artists: [
            {
              name: '박수빈',
              role: 'scripter',
              email: null,
              id: 'SoobinP',
            },
            {
              name: '정은민',
              role: 'scripter',
              email: null,
              id: 'EunminJ',
            },
            {
              name: '박형규',
              role: 'painter',
              email: null,
              id: 'hkpark',
            },
            {
              name: '이국종',
              role: 'original',
              email: null,
              id: 'hbooks',
            },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 31,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 78,
          previousRank: 78,
          updatedAt: 1670572427335,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6262255336620032/images/tall.jpg?width=130',
        },
        {
          id: 6099425048199168,
          alias: 'soyang_haechi',
          title: '소양공주와 해치',
          artists: [
            {
              name: '스튜디오 웨이브',
              role: 'writer',
              email: null,
              id: 'studioweiib',
            },
          ],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 79,
          previousRank: 79,
          updatedAt: 1662365400893,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6099425048199168/images/tall.jpg?width=130',
        },
        {
          id: 5016813088342016,
          alias: 'saram',
          title: '사람의 사이로',
          artists: [
            {
              name: '김보통',
              role: 'writer',
              email: null,
              id: 'kimbotong',
            },
          ],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 36,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 80,
          previousRank: 80,
          updatedAt: 1663742901519,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5016813088342016/images/tall.jpg?width=130',
        },
      ],
    },
  },
  {
    data: {
      hasNext: false,
      count: 100,
      comicRankList: [
        {
          id: 5054309770330112,
          alias: 'unbalance_as',
          title: '언밸런스X2 AS',
          artists: [
            {
              name: '임달영',
              role: 'scripter',
              email: null,
              id: 'imdalyoung',
            },
            {
              name: '이혜성',
              role: 'painter',
              email: null,
              id: 'leehyesung',
            },
            {
              name: '디투컴퍼니',
              role: 'publisher',
              email: null,
              id: 'd2company',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 81,
          previousRank: 81,
          updatedAt: 1573551253836,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5054309770330112/images/tall.jpg?width=130',
        },
        {
          id: 6558093126467584,
          alias: 'noegg',
          title: 'OX유정남',
          artists: [{ name: '도국', role: 'writer', email: null, id: 'iqzeo619' }],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 82,
          previousRank: 82,
          updatedAt: 1649654310106,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6558093126467584/images/tall.jpg?width=130',
        },
        {
          id: 6361678876246016,
          alias: 'gohomerun',
          title: '고홈런',
          artists: [{ name: '감대', role: 'writer', email: null, id: 'gamdae' }],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 83,
          previousRank: 83,
          updatedAt: 1520223539818,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6361678876246016/images/tall.jpg?width=130',
        },
        {
          id: 5196968141258752,
          alias: 'bolcom',
          title: '볼콤성의 유령',
          artists: [
            {
              name: '마레',
              role: 'writer',
              email: null,
              id: 'mareaestatis',
            },
          ],
          schedule: { periods: ['TUE'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 7,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 84,
          previousRank: 84,
          updatedAt: 1520223484768,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5196968141258752/images/tall.jpg?width=130',
        },
        {
          id: 5756808370585600,
          alias: 'pa',
          title: '파라노이드 안드로이드',
          artists: [{ name: '쏘요', role: 'writer', email: null, id: 'XOYO' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 10,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 85,
          previousRank: 85,
          updatedAt: 1666252927844,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5756808370585600/images/tall.jpg?width=130',
        },
        {
          id: 4932650884661248,
          alias: 'otaku',
          title: '덕후의 여자',
          artists: [
            {
              name: '허윤화',
              role: 'scripter',
              email: null,
              id: 'heoyunhwa',
            },
            { name: '다가비', role: 'painter', email: null, id: 'dagabi' },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 7,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 86,
          previousRank: 86,
          updatedAt: 1548989371286,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4932650884661248/images/tall.jpg?width=130',
        },
        {
          id: 5873525665628160,
          alias: 'kimbotong_fullmoon',
          title: '보름달 식당',
          artists: [
            {
              name: '김보통',
              role: 'writer',
              email: null,
              id: 'kimbotong',
            },
          ],
          schedule: { periods: ['THU', 'TUE'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 13,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 87,
          previousRank: 87,
          updatedAt: 1662452373211,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5873525665628160/images/tall.jpg?width=130',
        },
        {
          id: 4783477027897344,
          alias: 'dream_up',
          title: '드림 업!',
          artists: [
            { name: '탐린', role: 'scripter', email: null, id: 'tamlin' },
            {
              name: '박정열',
              role: 'painter',
              email: null,
              id: 'parkjungyeul',
            },
            {
              name: '디투컴퍼니',
              role: 'publisher',
              email: null,
              id: 'd2company',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 88,
          previousRank: 89,
          updatedAt: 1543824195925,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/4783477027897344/images/tall.jpg?width=130',
        },
        {
          id: 6449374706532352,
          alias: 'kasane',
          title: '카사네',
          artists: [
            {
              name: '마쓰우라 다루마',
              role: 'writer',
              email: null,
              id: 'darumamatsuura',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 89,
          previousRank: 90,
          updatedAt: 1562727206976,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6449374706532352/images/tall.jpg?width=130',
        },
        {
          id: 6128037428264960,
          alias: 'flowertaro',
          title: '꽃점 봐 드립니다',
          artists: [{ name: '주은', role: 'writer', email: null, id: 'jangjueun' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'scheduled',
          isPrint: false,
          currentRank: 90,
          previousRank: 91,
          updatedAt: 1627355637741,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6128037428264960/images/tall.jpg?width=130',
        },
        {
          id: 6485512691384320,
          alias: 'arrogance',
          title: '오만과 낭만',
          artists: [
            {
              name: '김설희',
              role: 'scripter',
              email: null,
              id: 'kimseolhui',
            },
            {
              name: '정과장',
              role: 'painter',
              email: null,
              id: 'jeonggwajang',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 11,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 91,
          previousRank: 92,
          updatedAt: 1568855746709,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6485512691384320/images/tall.jpg?width=130',
        },
        {
          id: 5134783918505984,
          alias: 'the_concours',
          title: '더 콩쿠르',
          artists: [
            {
              name: '정설화',
              role: 'writer',
              email: null,
              id: 'jeongseolhwa',
            },
            {
              name: '서울미디어코믹스',
              role: 'publisher',
              email: null,
              id: 'seoulmediacomics',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 5,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 92,
          previousRank: 93,
          updatedAt: 1596592164888,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5134783918505984/images/tall.jpg?width=130',
        },
        {
          id: 6227818152787968,
          alias: 'cranberry_juice',
          title: '데스크레센도',
          artists: [
            {
              name: '빌뱅',
              role: 'scripter',
              email: null,
              id: 'villvang',
            },
            {
              name: '턱시도펭귄',
              role: 'painter',
              email: null,
              id: 'tuxedopg',
            },
          ],
          schedule: { periods: ['SUN'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 4,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 93,
          previousRank: 94,
          updatedAt: 1649322872738,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6227818152787968/images/tall.jpg?width=130',
        },
        {
          id: 6343470570012672,
          alias: '2nd_manhwaking_private',
          title: '볕내 [제2회 세계만화공모전 수상작]',
          artists: [{ name: '박혜민', role: 'writer', email: null, id: 'hyemin' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 94,
          previousRank: 96,
          updatedAt: 1520223538861,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6343470570012672/images/tall.jpg?width=130',
        },
        {
          id: 1005,
          alias: '1st_manhwaking_wish',
          title: '기도(祈り)  [제1회 세계만화공모전 수상작]',
          artists: [{ name: '은송', role: 'writer', email: null, id: 'eunsong' }],
          schedule: { periods: ['WED'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 95,
          previousRank: 97,
          updatedAt: 1520223455801,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/1005/images/tall.jpg?width=130',
        },
        {
          id: 5156658229805056,
          alias: 'antique',
          title: '골동',
          artists: [{ name: '권동현', role: 'writer', email: null, id: 'siang' }],
          schedule: { periods: ['MON'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'completed',
          isPrint: false,
          currentRank: 96,
          previousRank: 98,
          updatedAt: 1550038311180,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5156658229805056/images/tall.jpg?width=130',
        },
        {
          id: 6655431101120512,
          alias: 'brides_for_king',
          title: '채홍사',
          artists: [
            {
              name: '헤드플레이',
              role: 'scripter',
              email: null,
              id: 'headplay',
            },
            { name: '오트', role: 'painter', email: null, id: 'ots' },
            {
              name: '지티이엔티',
              role: 'publisher',
              email: null,
              id: 'gtent',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 2,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 97,
          previousRank: 99,
          updatedAt: 1536812352310,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6655431101120512/images/tall.jpg?width=130',
        },
        {
          id: 5215342426980352,
          alias: 'guilty_innocence',
          title: '길티 이노센스 [연재]',
          artists: [
            { name: '윤한', role: 'writer', email: null, id: 'yunhan' },
            {
              name: '대원씨아이',
              role: 'publisher',
              email: null,
              id: 'dwci',
            },
          ],
          schedule: { periods: ['FRI'], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 3,
          contentsState: 'scheduled',
          isPrint: true,
          currentRank: 98,
          previousRank: 100,
          updatedAt: 1671081678971,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/5215342426980352/images/tall.jpg?width=130',
        },
        {
          id: 6562201909592064,
          alias: 'let_well_alone',
          title: '그대로 좋아!',
          artists: [{ name: '보배', role: 'writer', email: null, id: 'haksan' }],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 99,
          previousRank: 101,
          updatedAt: 1547787169506,
          thumbnailSrc:
            'https://ccdn.lezhin.com/v2/comics/6562201909592064/images/tall.jpg?width=130',
        },
        {
          id: 799,
          alias: 'acca',
          title: 'ACCA 13구 감찰과',
          artists: [
            {
              name: '오노 나츠메',
              role: 'writer',
              email: null,
              id: 'natsumeono',
            },
            {
              name: '넥스큐브',
              role: 'publisher',
              email: null,
              id: 'nexcube',
            },
          ],
          schedule: { periods: [], anchor: 0 },
          genres: ['drama'],
          badges: '',
          freedEpisodeSize: 1,
          contentsState: 'completed',
          isPrint: true,
          currentRank: 100,
          previousRank: 102,
          updatedAt: 1556080257101,
          thumbnailSrc: 'https://ccdn.lezhin.com/v2/comics/799/images/tall.jpg?width=130',
        },
      ],
    },
  },
];

export default dramaComicDatas;
